version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: codeacademy-mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-}
    restart: always
    networks:
      - app-network

  server:
    build: 
      context: ./server
    container_name: codeacademy-server
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://${MONGO_USERNAME:+${MONGO_USERNAME}:${MONGO_PASSWORD}@}mongodb:27017/codeacademy${MONGO_AUTH_SOURCE:+?authSource=${MONGO_AUTH_SOURCE}}
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    restart: always
    networks:
      - app-network

  client:
    build:
      context: ./client
    container_name: codeacademy-client
    depends_on:
      - server
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local